/**:
  ros__parameters:

camera_node:
  ros__parameters:
    camera_index: 0
    frame_width: 640
    frame_height: 480
    fps: 30
    publish_compressed: true
    jpeg_quality: 50

thruster_node:
  ros__parameters:
    armed: false

sensor_node:
  ros__parameters:
    publish_rate: 10.0

status_node:
  ros__parameters:
    publish_rate: 1.0
